alias ll='ls -altr'
export http_proxy="http://wwwproxy.unimelb.edu.au:8000"
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy

export NVM_DIR="/home/freshdesk/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm